name: Docker Build & Push + ECS Deploy

on:
  push:
    branches:
      - master  # Only trigger when code is pushed/merged into master

jobs:
  docker_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate dynamic version
        id: version
        run: |
          VERSION="v1.0-$(date +%Y%m%d%H%M)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          VERSION=${{ steps.version.outputs.version }}
          docker build -t anjali140402/bang:${VERSION} -t anjali140402/bang:latest .
          docker push anjali140402/bang:${VERSION}
          docker push anjali140402/bang:latest

      - name: Deploy to ECS using latest image
        run: |
          aws ecs update-service \
            --cluster anji-test \
            --service anji-service \
            --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # or your region
