name: Auto Merge + Docker Build & Push

on:
  push:
    branches:
      - develop
      - master

jobs:
  merge_to_master:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Authenticate with GitHub
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/anjalisvaapta14/AWS_CICD.git

      - name: Merge develop into master
        run: |
          git checkout master
          git merge origin/develop --no-edit
          git push origin master

  docker_deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate dynamic version
        id: version
        run: |
          VERSION="v1.0-$(date +%Y%m%d%H%M)"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        run: |
          VERSION=${{ steps.version.outputs.version }}
          docker build -t anjali1404/bang:${VERSION} -t anjali1404/bang:latest .
          docker push anjali1404/bang:${VERSION}
          docker push anjali1404/bang:latest

      - name: Deploy to ECS using latest image
        run: |
          aws ecs update-service \
            --cluster anji-test \
            --service anji-service \
            --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  # or your region